### ISSUE TITLE
Installing aurelia-cookies through npm and then compiling project with tsc causes error

### ISSUE THREAD

**Issue by chrisspiking** [aurelia-plugins/aurelia-plugins-cookies#2]
**I'm submitting a bug report**
- **Framework Version:**
  1.1.1

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.10
- **Node Version:**
  6.6.0
  
  
- **NPM Version:**
  3.10.7
  
  
- **JSPM OR Webpack AND Version**
  Not using jspm/webpack
  
  
- **Browser:**
  N/A
- **Language:**
  all | TypeScript 1.8.6 |

**Current behavior:**
After adding "aurelia-cookies": "^1.1.1" to my npm dependencies and installing via npm install I am trying to compile my typescript into js using tsc, however when running tsc it throws the following error:

node_modules/aurelia-cookies/dist/aurelia-cookies.d.ts(20,1): error TS1128: Declaration or statement expected.
node_modules/aurelia-cookies/dist/aurelia-cookies.d.ts(20,8): error TS2304: Cannot find name 'declare'.
node_modules/aurelia-cookies/dist/aurelia-cookies.d.ts(20,16): error TS1005: ';' expected.

Looking at where the error is being thrown in aurelia-cookies.d.ts it's complaining about the following:

export declare {
  Cookies
};

Is this correct syntax for a d.ts file? If I comment out those three lines tsc completes without error.

**Expected/desired behavior:**

- **What is the expected behavior?**
  tsc compilation of project with aurelia-cookies as dependency completes successfully.
- **What is the motivation / use case for changing the behavior?**
  No behaviour change

**Comment by bartlenaerts** [comment]
The Typescript file was automatic generated from the build tasks in aurelia-skeleton-plugin. As I'm using Webpack with vanilla JS, I have to dive into Typescript actually to find out. If you have any ideas or solutions, please feel free to commit.
